/*
 *Angus Henry 
 *24/04/2018 
 *This program convets different imperial mesuraments to metric
 *formICS3UUNIT3PROGRAMSU3A3ConvertMe.java
 */

package ICS3UUNIT3PROGRAMSU3A3ConvertMe;
 import java.text.DecimalFormat;
/**
 *
 * @author anhen3335
 */
public class formICS3UUNIT3PROGRAMSU3A3ConvertMe extends javax.swing.JFrame {
    /**
     * Creates new form formICS3UUNIT3PROGRAMSU3A3ConvertMe
     */
    public formICS3UUNIT3PROGRAMSU3A3ConvertMe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeTitle = new javax.swing.JLabel();
        labelConversion = new javax.swing.JLabel();
        labelLength = new javax.swing.JLabel();
        textConversion = new javax.swing.JTextField();
        textLength = new javax.swing.JTextField();
        buttonConvert = new javax.swing.JButton();
        labelAnswer = new javax.swing.JLabel();
        labelFtoC = new javax.swing.JLabel();
        labelYtoM = new javax.swing.JLabel();
        labelMtoK = new javax.swing.JLabel();
        labelCtoI = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeTitle.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        labeTitle.setText("Linear Conversion");
        jPanel1.add(labeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 188, 45));

        labelConversion.setText("What are you Converting?");
        jPanel1.add(labelConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 36));

        labelLength.setText("Length (Imperial)");
        jPanel1.add(labelLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 118, 49));

        textConversion.setText("Put number here to choose.");
        textConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConversionActionPerformed(evt);
            }
        });
        jPanel1.add(textConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 330, 36));

        textLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLengthActionPerformed(evt);
            }
        });
        jPanel1.add(textLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 168, 330, 36));

        buttonConvert.setText("Convert");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 222, 500, -1));
        jPanel1.add(labelAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 250, 600, 28));

        labelFtoC.setText("Feet to Centimeters:2");
        jPanel1.add(labelFtoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, -1));

        labelYtoM.setText("Yards to Meters: 3");
        jPanel1.add(labelYtoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, -1));

        labelMtoK.setText("Miles to Kilometers: 4");
        jPanel1.add(labelMtoK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        labelCtoI.setText("Inches to Centimeters: 1");
        jPanel1.add(labelCtoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, -1));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConversionActionPerformed

    private void textLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLengthActionPerformed

    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
        // Declare our variables
        int meas;
        double length;
        meas = Integer.parseInt(textConversion.getText ());
        length = Double.parseDouble (textLength.getText ());
        // Create the decimal format
        DecimalFormat x = new DecimalFormat("#.##");
        // See what conversion we must do
        if (meas == 1){
        labelAnswer.setText  (x.format(inchesToCentimeters(length)) + "cm");   
        
        }
        else if (meas == 2){
        labelAnswer.setText  (x.format(feetToCentimeters (length)) + "cm");
            
        }
        else if (meas == 3){
         labelAnswer.setText  (x.format(yardsToMeters (length)) + "m");   
           
        }
        else if (meas == 4){
           labelAnswer.setText  (x.format( milesToKilometers (length)) + "km");     
            
        }
        else {
          labelAnswer.setText  ( "That is not a valib conversion type, please enter a numb between 1 and 4");  
        }
    }//GEN-LAST:event_buttonConvertActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        //
    }//GEN-LAST:event_jMenu1ActionPerformed
// Exit System
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    // Different methods for each calculation  
    private double inchesToCentimeters(double length){
    return length * 2.54;
}
       private double feetToCentimeters(double length){
      return length * 30;
       }
       private double yardsToMeters(double length) {
       return length * 0.91;  
       }
       private double milesToKilometers(double length){
      return length * 1.6;
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formICS3UUNIT3PROGRAMSU3A3ConvertMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formICS3UUNIT3PROGRAMSU3A3ConvertMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formICS3UUNIT3PROGRAMSU3A3ConvertMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formICS3UUNIT3PROGRAMSU3A3ConvertMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formICS3UUNIT3PROGRAMSU3A3ConvertMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConvert;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeTitle;
    private javax.swing.JLabel labelAnswer;
    private javax.swing.JLabel labelConversion;
    private javax.swing.JLabel labelCtoI;
    private javax.swing.JLabel labelFtoC;
    private javax.swing.JLabel labelLength;
    private javax.swing.JLabel labelMtoK;
    private javax.swing.JLabel labelYtoM;
    private javax.swing.JTextField textConversion;
    private javax.swing.JTextField textLength;
    // End of variables declaration//GEN-END:variables
}